### ISSUE TITLE
 LEVEL-Shifter funktioniert nicht (ist aber auch nicht notwendig)

### ISSUE THREAD

**Issue by JanHBade** [Claus-E/teams2tasmota#4]
Hallo,

der beim Eigenbau verwendete LevelShifter kann so nicht funktionieren.

Eine Diode kann keine Spannung irgendwo oben drauf addieren, wenn dann fällt an ihr eine Spannung ab.

Bei all meinen bisher gebauten EPS + RGB Led Projekten war auch kein Level Shifter notwendig, auch 3,3V werden ohne Probleme von den LEDs als '1' erkannt.

**Comment by JanHBade** [comment]
funktioniert aber nur wenn die Diode richtig rum drin ist ;)

Imho ist die auf dem Bild bei dir falsch rum drin...

links funktioniert, rechts nicht

![grafik](https://user-images.githubusercontent.com/3524802/166224472-64bf9336-2fb4-4ada-af6a-eb1977b1b334.png)

**Comment by Claus-E** [comment]
Hallo Jan,

ja völlig richtig! Ich habe die Grafik korrigiert und die Diode umgedreht.

Wenn Du Deine Simulation noch vollständig haben willst, dann müsstest Du an den DIN noch die Eingangskapazität der RGBs anschließen, dann siehst Du weshalb bei mir parallel zur Diode noch ein Kondensator geschaltet wurde.

Gruß Claus
